name: yamler
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/AmrDeveloper/yamler
repository: https://github.com/AmrDeveloper/yamler.git
issue_tracker: https://github.com/AmrDeveloper/yamler/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.17.12
