name: yamler
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/AmrDeveloper/yamler

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
